#!/bin/bash

# apt -y install unzip

echo -e "\033[31m =============================================================\033[0m"
echo -e "\033[33m                 脚本名：  trace.sh \033[0m"
echo -e "\033[33m *原作者：@ztang；Github：https://github.com/zq/shell \033[0m"
echo -e "\033[34m *此脚本仅仅删减了测试用ip地址 \033[0m"
echo -e "\033[34m *运行后自动测试服务器回程到广州电信联通移动路由情况 \033[0m"
echo -e "\033[1;36m *此脚本发布在 http://vpsoff.com \033[0m"
echo -e "\033[31m =============================================================\033[0m"


# install besttrace
if [ ! -f "besttrace" ]; then
    wget https://github.com/zq/shell/raw/master/besttrace
    # unzip besttrace4linux.zip
    chmod +x besttrace
fi

## start to use besttrace

next() {
    printf "%-70s\n" "-" | sed 's/\s/-/g'
}

#clear
next

ip_list=(202.96.128.166 210.21.196.6 211.136.192.6)
ip_addr=(广州电信 广州联通 广州移动)
# ip_len=${#ip_list[@]}

for i in {0..2}
do
    echo ${ip_addr[$i]}
    ./besttrace -q 1 ${ip_list[$i]}
    next
done
