#!/bin/bash

# apt -y install unzip

echo -e "\033[31m =============================================================\033[0m"

echo -e "\033[33m                 脚本名：  vps回程路由测试 \033[0m"
echo -e "\033[33m              一键运行 wget -qO- git.io/Je2us | bash \033[0m"
echo -e "\033[34m *运行后自动测试服务器回程到广州电信联通移动路由情况* \033[0m"
echo -e "\033[34m   广州电信dns1 202.96.128.86                     \033[0m"
echo -e "\033[34m    广州电信dns1 202.96.134.33                    \033[0m"
echo -e "\033[34m    广州联通dns1 210.21.196.6                     \033[0m"
echo -e "\033[34m    广州联通dns1 221.5.88.8                       \033[0m"
echo -e "\033[34m    广州移动dns1 211.136.192.6                    \033[0m"
echo -e "\033[34m    广州移动dns2 120.196.165.24                   \033[0m"
echo -e "\033[34m    深圳电信     183.56.167.125                   \033[0m"
echo -e "\033[34m    中山电信     183.60.40.97                     \033[0m"
echo -e "\033[34m    广州移动     221.183.63.125                   \033[0m"

echo -e "\033[31m =============================================================\033[0m"


# install besttrace
if [ ! -f "besttrace" ]; then
    wget https://github.com/liubo20190515/trace/blob/master/besttrace.zip
    # unzip besttrace4linux.zip
    chmod +x besttrace
fi

## start to use besttrace

next() {
    printf "%-70s\n" "-" | sed 's/\s/-/g'
}

#clear
next

ip_list=(202.96.128.86 202.96.134.33 210.21.196.6 221.5.88.88 211.136.192.6 120.196.165.24 183.56.167.125 183.60.40.97 221.183.63.125)
ip_addr=(广州电信dns1 广州电信dns2 广州联通dns1 广州联通dns2 广州移动dns1 广州移动dns2 深圳电信 中山电信 广州移动)
# ip_len=${#ip_list[@]}

for i in {0..8}
do
    echo ${ip_addr[$i]}
    ./besttrace -q 1 ${ip_list[$i]}
    next
done
